### ISSUE TITLE
How do I uninstall ?

### ISSUE THREAD

**Issue by RohanGautam** [cra0zy/code-nautilus#10]
Hey! First of all, thanks for making this but I have to remove this due to some reasons. Is there anything I could do/ does an uninstall script exist to help me remove it?

**Comment by cra0zy** [comment]
Oh, I should definitely add this to the README, simply do the following to remove it:
```
rm -f ~/.local/share/nautilus-python/extensions/VSCodeExtension.py
rm -f ~/.local/share/nautilus-python/extensions/code-nautilus.py
```
