### ISSUE TITLE
Allow re-ordering of VS Code context menu item

### ISSUE THREAD

**Issue by Sharpiro** [cra0zy/code-nautilus#11]
I really love this extension, so thank you.

I think it would be helpful to be able to configure the order of where "Open Code Here" appears in the context menu.  

This may not be possible at all with Nautilus.  However, if it is possible to modify the order, I think since the number of context menu items that appears is influenced by what kind of item you are clicking on, adding a "always appear at bottom" or "always appear at top" would be useful as regardless of what you are clicking on, you will always know where the VS Code context menu item will be.

**Comment by cra0zy** [comment]
Nautilus does not allow ordering of extensions, the best you can do is trick it by naming an extension in a certain way I think.

**Comment by Sharpiro** [comment]
darn, thanks
