### ISSUE TITLE
"Open Code" appear twice in nautilus menu

### ISSUE THREAD

**Issue by n1st** [cra0zy/code-nautilus#4]
Hi craOzy,

Great extension, thanks for sharing it.

Just installed it and have just little issue: in Fedora30, GNOME nautilus 3.32.1, the link "open Code" appear twice in the menu. Same thing for "Open In Code" for files.

![codeNautilus_issueDoublon](https://user-images.githubusercontent.com/35531873/61450063-8975ef80-a956-11e9-8325-6206bda51333.png)

Do you have an idea how to resolv this issue?

**Comment by cra0zy** [comment]
Hmm, give me the output of `ls -l ~/.local/share/nautilus-python/extensions/`, I assume you installed the extension multiple times?

**Comment by nicolasdestor** [comment]
```
#ls -l ~/.local/share/nautilus-python/extensions/
total 8
-rw-rw-r--. 1 user group 1825 18 juil. 16:00 code-nautilus.py
drwxr-xr-x. 2 user group 4096 18 juil. 16:00 __pycache__
```

If I removed it manually, the both links disapear. After re-install it, both link appear again.

**Comment by cra0zy** [comment]
Hmm, strange...

On a related note, I use Fedora 30 as my daily driver, everything works fine on my machine.

**Comment by nicolasdestor** [comment]
Interesting.What about the version of Nautilus, is it the same? 

I don't really think the problem come from your extension, that seems to be more a "bug" on nautilus side.

**Comment by cra0zy** [comment]
Same version.

**Comment by n1st** [comment]
Solved after cleaning some of user's config files. Can't tell what exactly, but definitively not a issue on your side. Thanks again for your sharing.

**Comment by cra0zy** [comment]
:+1:

**Comment by aadilayub** [comment]
@ndestor could you share what config files you removed? I'm getting the same error here. "Open in Code" is showing up twice in the menu
