### ISSUE TITLE
Provide an AUR package

### ISSUE THREAD

**Issue by cra0zy** [cra0zy/code-nautilus#6]
I will probably work only on the .rpm package as Fedora is what I use, however I wouldn't mind maintaining other packages as well.

**Comment by tkit1994** [comment]
I have created a PKGBUILD file and it works for me. As a newbee, I can not make sure that there are no mistakes so I didn't upload it to aur, but it may be of help.
[PKGBUILD](https://gist.github.com/tkit1994/5056a5ac4ade1515baa46ff3168c8503)

**Comment by tkit1994** [comment]
I have submitted the PKGBUID to aur. Here is the package [code-nautilus-git](https://aur.archlinux.org/packages/code-nautilus-git/)

If you have an aur id, please tell me so that I can add you to co-maintainers.@cra0zy

**Comment by cra0zy** [comment]
I do, its same as github one, "cra0zy".

If you can, please submit the PKGBUILD stuff to this repo.

**Comment by tkit1994** [comment]
OK, I have added pkgbuild stuff and updated readme in https://github.com/cra0zy/code-nautilus/pull/9

**Comment by harry-cpp** [comment]
Just a heads up, I have changed my username so you are not surprised when you see a new name in AUR.
